select * from Clientes
select * from Profissionais
select * from Servicos
select * from Produtos
select * from Pecas
select * from Execucao
select * from ServicosExecutados
select * from Veiculos
select * from OrdensServico
